[workspace]
members = ["rap-*"]

[workspace.package]
version = "0.2.0"
authors = ["Renning Bruns <ren@renmail.net>"]
description = "Ren's ActivityPub stuff"

[package]
name = "rens-activity-pub"
version.workspace = true
edition = "2021"

[dependencies]
