[package]
name = "rap-client-cli"
version.workspace = true
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { workspace = true }
reqwest = { version = "0.11.20", features = ["json", "blocking"] }
